### ISSUE TITLE
How do I train on a new speaker?

### ISSUE THREAD

**Issue by jayavanth** [facebookresearch/loop#10]

**Comment by ytaigman** [comment]
Collect new samples for a new identity -- for example, you can overwrite identity 0 (follow the same convention as in data.py), and continue to train from your latest checkpoint (fine-tune) with it. This should work, although not very fast or efficient. Other techniques can be used for faster fitting (see subsection 3.2 in the paper).

**Comment by jayavanth** [comment]
I used `extract_feats.py` script to generate the `.npz` files, but I'm missing these arrays in the `.npz` files : `['text_features', 'audio_norminfo', 'text_norminfo', 'code2char', 'code2phone']` How do I get these arrays?

**Comment by jayavanth** [comment]
Ah, I see that it's commented. Let me try the extract script again

**Comment by jayavanth** [comment]
I fixed that. Now I'm getting this error when I start the training
```
python train.py --expName vctk --data data/vctk --noise 4 --seq-len 100 --epochs 90
WARNING:root:Experiment already exists!
INFO - 09/11/17 12:04:48 - 0:00:00 - Namespace(K=10, attention_alignment=0.05, batch_size=64, checkpoint='', clip_grad=0.5, data='data/vctk', epochs=90, expName='checkpoints/vctk', gpu=0, hidden_size=256, ignore_grad=10000.0, lr=0.0001, max_seq_len=1000, mem_size=20, noise=4, nspk=22, output_size=63, seed=1, seq_len=100, visualize=False, vocabulary_size=44)
INFO - 09/11/17 12:04:48 - 0:00:00 - Building dataset.
INFO - 09/11/17 12:04:48 - 0:00:00 - Dataset ready!
Train epoch 1:   0%|                                                                                                           | 0/130 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 211, in <module>
    main()
  File "train.py", line 199, in main
    train(model, criterion, optimizer, epoch, train_losses)
  File "train.py", line 104, in train
    for full_txt, full_feat, spkr in train_enum:
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 833, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 212, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 239, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 41, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/jay/Onu/demo/loop/data.py", line 45, in collate_by_input_length
    new_batch = [x for x in batch if x[1].size(0) < max_seq_len]
RuntimeError: dimension 0 out of range of 0D tensor at /b/wheel/pytorch-src/torch/lib/TH/generic/THTensor.c:24
```

**Comment by abhinonymous** [comment]
You would probably get this error when one of your npz files has  "audio_features" array of shape 0.

**Comment by jaxlinksync** [comment]
@abhinonymous Hi, how do we prevent this?

**Comment by PetrochukM** [comment]
^ Ditto
