### ISSUE TITLE
error on generate.py execution

### ISSUE THREAD

**Issue by abhinonymous** [facebookresearch/loop#3]
I get an error upon executing:
python generate.py  --npz data/vctk/numpy_features_valid/p318_212.npz --spkr 13 --checkpoint models/vctk/bestmodel.pth

```
(gpu_13) abhinav@ubuntu11:~/.../loop$ python generate.py  --npz data/vctk/numpy_features_valid/p318_212.npz --spkr 13 --checkpoint models/vctk/bestmodel.pth
Traceback (most recent call last):
  File "generate.py", line 153, in <module>
    main()
  File "generate.py", line 132, in main
    out, attn = model([txt, spkr], feat)
  File "/home/abhinav/tensorflow/gpu_13/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/software/LM_stash/abhinav/projects/tts/loop/model.py", line 247, in forward
    context, ident = self.encoder(src[0], src[1])
  File "/home/abhinav/tensorflow/gpu_13/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/software/LM_stash/abhinav/projects/tts/loop/model.py", line 66, in forward
    outputs = self.lut_p(input)
  File "/home/abhinav/tensorflow/gpu_13/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/abhinav/tensorflow/gpu_13/local/lib/python2.7/site-packages/torch/nn/modules/sparse.py", line 94, in forward
    self.scale_grad_by_freq, self.sparse
  File "/home/abhinav/tensorflow/gpu_13/local/lib/python2.7/site-packages/torch/nn/_functions/thnn/sparse.py", line 48, in forward
    cls._renorm(indices, weight, max_norm, norm_type)
TypeError: _renorm() takes exactly 5 arguments (4 given)

```

I have followed all steps in the Setup segment

**Comment by soumith** [comment]
are you using pytorch 0.1.12 as theyve mentioned in the README?

**Comment by soumith** [comment]
what is print(torch.__version__)

**Comment by abhinonymous** [comment]
thanks, that was it
