### ISSUE TITLE
' out of memory' accrued when training with single speaker

### ISSUE THREAD

**Issue by hepower** [facebookresearch/loop#36]
Hi, 

Below error accrued when training with single speaker:
Train (loss 63.31) epoch 1:   3%|████▍                                                                                                                           | 1/29 [00:23<11:10, 23.93s/it]THCudaCheck FAIL file=/b/wheel/pytorch-src/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 211, in <module>
    main()
  File "train.py", line 199, in main
    train(model, criterion, optimizer, epoch, train_losses)
  File "train.py", line 122, in train
    loss.backward()
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 146, in backward
    self._execution_engine.run_backward((self,), (gradient,), retain_variables)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/_functions/linear.py", line 24, in backward
    grad_weight = torch.mm(grad_output.t(), input)
RuntimeError: cuda runtime error (2) : out of memory at /b/wheel/pytorch-src/torch/lib/THC/generic/THCStorage.cu:66

Could you please help?

**Comment by hepower** [comment]
I use the default config which was introduced in the Readme.md, data is my own data:
python train.py --noise 1 --expName test_init --seq-len 1600 --max-seq-len 1600 --data data/test --nspk 1 --lr 1e-5 --epochs 10 --gup 1

**Comment by hepower** [comment]
Ok. I have reduce the '--seq-len' and '--max-seq-len' to 1500, it seems could start the training fine.
