### ISSUE TITLE
Blizzard Model

### ISSUE THREAD

**Issue by PetrochukM** [facebookresearch/loop#44]
Can't use the Blizzard model without the original training data:
```
Traceback (most recent call last):
  File "generate.py", line 156, in <module>
    main()
  File "generate.py", line 83, in main
    train_dataset = NpzFolder(train_args.data + '/numpy_features')
  File "/home/michael/Desktop/loop/data.py", line 84, in __init__
    self.NPZ_EXTENSION))
RuntimeError: Found 0 npz in subfolders of: data/blizzard/numpy_features
Supported image extensions are: npz
```
Looks `generate.py` uses parameters in the training data to `generate.py`

**Comment by PetrochukM** [comment]
Hi!

Thanks for your quick work. The code is still dependent:

Line 83, generate.py:
`train_dataset = NpzFolder(train_args.data + '/numpy_features')`

Line 156, utils.py:
`fid = open(norm_info_file, 'rb')`

**Comment by adampolyak** [comment]
Right, it was still dependent on the norm file.

Check it out now, you'll need to download blizzard model again to obtain the norm file.

**Comment by PetrochukM** [comment]
Okay! I'll need to download the blizzard model and extract features to obtain the norm file, right?

**Comment by adampolyak** [comment]
I've added the norm information to the model zip. So just download the
model as in the documentation.

The generation script will find it.

**Comment by PetrochukM** [comment]
Perfect! Thanks worked well!!
