### ISSUE TITLE
Any clue? Missing norm_info_mgc_lf0_vuv_bap_63_MVN.dat while prepossessing Lj Speech Dataset.

### ISSUE THREAD

**Issue by niravpatel2008** [facebookresearch/loop#48]
I am getting below error while preprocessing Lj Speech data set.

```
Traceback (most recent call last):
  File "extract_feats.py", line 1406, in <module>
    save_numpy_features()
  File "extract_feats.py", line 853, in save_numpy_features
    shutil.copy2(audio_norm_source, audio_norm_dest)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/jax/latest_features/final_acoustic_data/norm_info_mgc_lf0_vuv_bap_63_MVN.dat'
```

**Comment by PetrochukM** [comment]
Yup. Remember to uncomment these lines: https://gist.github.com/kastnerkyle/cc0ac48d34860c5bb3f9112f4d9a0300#file-extract_feats-py-L1029

**Comment by niravpatel2008** [comment]
@PetrochukM will try soon and let you know. 

thanks

**Comment by niravpatel2008** [comment]
@PetrochukM 

After uncommenting i got faced following error :

`2018-03-29 11:15:23,161 INFO      acoustic_comp: processing file    1 of    1 :                                                                     /root/preprocess/latest_features/merlin/egs/build_your_own_voice/s1/experiments/                                                                    my_new_voice/acoustic_model/data/nn_mgc_lf0_vuv_bap_63/*.cmp
Traceback (most recent call last):
  File "/root/preprocess/latest_features/merlin/src/run_merlin.py", line 1175, i                                                                    n <module>
    main_function(cfg)
  File "/root/preprocess/latest_features/merlin/src/run_merlin.py", line 693, in                                                                     main_function
    acoustic_worker.prepare_nn_data(in_file_list_dict, nn_cmp_file_list, cfg.in_                                                                    dimension_dict, cfg.out_dimension_dict)
  File "/root/preprocess/latest_features/merlin/src/frontend/acoustic_base.py",                                                                     line 122, in prepare_nn_data
    self.prepare_data(in_file_list_dict, out_file_list, in_dimension_dict, out_d                                                                    imension_dict)
  File "/root/preprocess/latest_features/merlin/src/frontend/acoustic_compositio                                                                    n.py", line 126, in prepare_data
    features, frame_number = io_funcs.load_binary_file_frame(in_file_name, in_fe                                                                    ature_dim)
  File "/root/preprocess/latest_features/merlin/src/io_funcs/binary_io.py", line                                                                     64, in load_binary_file_frame
    fid_lab = open(file_name, 'rb')
IOError: [Errno 2] No such file or directory: '/root/preprocess/latest_features/                                                                    merlin/egs/build_your_own_voice/s1/experiments/my_new_voice/acoustic_model/data/                                                                    mgc/*.mgc'
+ echo 'All successfull!! Your demo voice is ready :)'
All successfull!! Your demo voice is ready :)
Feature extraction complete!
Traceback (most recent call last):
  File "extract_feats.py", line 1407, in <module>
    save_numpy_features()
  File "extract_feats.py", line 853, in save_numpy_features
    shutil.copy2(audio_norm_source, audio_norm_dest)
  File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/root/preprocess/latest_features/                                                                    final_acoustic_data/norm_info_mgc_lf0_vuv_bap_63_MVN.dat'`

**Comment by PetrochukM** [comment]
People were able to figure it out in this post: https://github.com/facebookresearch/loop/issues/11

Does that help?

**Comment by niravpatel2008** [comment]
@PetrochukM have earlier tried those solutions but still having issue. may be i am struggling because i am new to synthesizing.

**Comment by sausax** [comment]
@niravpatel2008 Any success with LJ Dataset ?

**Comment by wanshun123** [comment]
I had this error and had to install bandmat https://pypi.org/project/bandmat/ and lxml https://lxml.de/installation.html (in the logs many lines above there was a module not found error as it was trying to import these libraries).
