### ISSUE TITLE
invalid combination of arguments error in training or generating

### ISSUE THREAD

**Issue by jinserk** [facebookresearch/loop#5]
Once I've installed and tried to train or generate as described in the readme, it makes an invalid combination of arguments error as following:
```
$ python train.py --expName vctk --data data/vctk --noise 4 --seq-len 100 --epochs 90
INFO - 09/06/17 09:30:25 - 0:00:00 - Namespace(K=10, attention_alignment=0.05, batch_size=64, checkpoint='', clip_grad=0.5, data='data/vctk', epochs=90, expName='checkpoints/vctk', gpu=0, hidden_size=256, ignore_grad=10000.0, lr=0.0001, max_seq_len=1000, mem_size=20, noise=4, nspk=22, output_size=63, seed=1, seq_len=100, vocabulary_size=44)
INFO - 09/06/17 09:30:25 - 0:00:00 - Building dataset.
INFO - 09/06/17 09:30:25 - 0:00:00 - Dataset ready!
Traceback (most recent call last):
  File "train.py", line 207, in <module>
    main()
  File "train.py", line 175, in main
    model = Loop(args)
  File "/d2/jbaik/loop/model.py", line 217, in __init__
    self.decoder = Decoder(opt)
  File "/d2/jbaik/loop/model.py", line 137, in __init__
    opt.attention_alignment)
  File "/d2/jbaik/loop/model.py", line 87, in __init__
    self.N_a = getLinear(mem_elem, 3*K)
  File "/d2/jbaik/loop/model.py", line 15, in getLinear
    return nn.Sequential(nn.Linear(dim_in, dim_in/10),
  File "/home/jbaik/.pyenv/versions/3.6.2/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 41, in __init__
    self.weight = Parameter(torch.Tensor(out_features, in_features))
TypeError: torch.FloatTensor constructor received an invalid combination of arguments - got (float, int), but expected one of:
 * no arguments
 * (int ...)
      didn't match because some of the arguments have invalid types: (float, int)
 * (torch.FloatTensor viewed_tensor)
 * (torch.Size size)
 * (torch.FloatStorage data)
 * (Sequence data)
```
Could you let me get some hint to handle this? Thanks!

**Comment by adampolyak** [comment]
Can you try to execute the code using Python2.7? Currently, the code doesn't support Python3.6.

**Comment by jinserk** [comment]
Hmm.. I've checked python 2.7.13 with pytorch 0.1.12+ccd5f4d, but the error still occurs:
```
$ python generate.py  --npz data/vctk/numpy_features_valid/p318_212.npz --spkr 13 --checkpoint models/vctk/bestmodel.pth
Traceback (most recent call last):
  File "generate.py", line 153, in <module>
    main()
  File "generate.py", line 91, in main
    model = Loop(train_args)
  File "/d2/jbaik/loop/model.py", line 217, in __init__
    self.decoder = Decoder(opt)
  File "/d2/jbaik/loop/model.py", line 137, in __init__
    opt.attention_alignment)
  File "/d2/jbaik/loop/model.py", line 87, in __init__
    self.N_a = getLinear(mem_elem, 3*K)
  File "/d2/jbaik/loop/model.py", line 15, in getLinear
    return nn.Sequential(nn.Linear(dim_in, round(dim_in/10)),
  File "/home/jbaik/.pyenv/versions/2.7.13/lib/python2.7/site-packages/torch/nn/modules/linear.py", line 37, in __init__
    self.weight = Parameter(torch.Tensor(out_features, in_features))
TypeError: torch.FloatTensor constructor received an invalid combination of arguments - got (float, int), but expected one of:
 * no arguments
 * (int ...)
      didn't match because some of the arguments have invalid types: (float, int)
 * (torch.FloatTensor viewed_tensor)
 * (torch.Size size)
 * (torch.FloatStorage data)
 * (Sequence data)
```
```
$ python
Python 2.7.13 (default, Sep  6 2017, 09:48:35) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'0.1.12+ccd5f4d'
>>> 
```

**Comment by jinserk** [comment]
Thanks @adampolyak. Yes, it works with Python 2.7 and PyTorch 0.1.12.
