### ISSUE TITLE
Error while generating sample speech from pretrained model

### ISSUE THREAD

**Issue by ajinkyakulkarni14** [facebookresearch/loop#56]
I am trying to generate sample speech with voiceloop on pretrained model and getting following error, 

any help is appreciated !!

python generate.py  --text "hello world" --spkr 1 --checkpoint models/vctk/bestmodel.pth

Traceback (most recent call last):
  File "generate.py", line 168, in <module>
    main()
  File "generate.py", line 102, in main
    model = Loop(train_args)
  File "/home/vkulkarn/speech_processing/pytorch_tts/voiceloop/loop/model.py", line 217, in __init__
    self.decoder = Decoder(opt)
  File "/home/vkulkarn/speech_processing/pytorch_tts/voiceloop/loop/model.py", line 137, in __init__
    opt.attention_alignment)
  File "/home/vkulkarn/speech_processing/pytorch_tts/voiceloop/loop/model.py", line 87, in __init__
    self.N_a = getLinear(mem_elem, 3*K)
  File "/home/vkulkarn/speech_processing/pytorch_tts/voiceloop/loop/model.py", line 15, in getLinear
    return nn.Sequential(nn.Linear(dim_in, dim_in/10),
  File "/home/vkulkarn/conda/anaconda3/envs/voice_loop/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 41, in __init__
    self.weight = Parameter(torch.Tensor(out_features, in_features))
TypeError: new() received an invalid combination of arguments - got (float, int), but expected one of:
 * (torch.device device)
 * (tuple of ints size, torch.device device)
      didn't match because some of the arguments have invalid types: (float, int)
 * (torch.Storage storage)
 * (Tensor other)
 * (object data, torch.device device)
      didn't match because some of the arguments have invalid types: (float, int)

**Comment by melaanya** [comment]
Are you sure that your PyTorch version is 0.1.12? The code is written for this version, there were some changes in PyTorch after

**Comment by ajinkyakulkarni14** [comment]
I install python 3.6, i change it to 2.7 and it worked !
