### ISSUE TITLE
Main Readme wav files are missing and first instruction doesn't work

### ISSUE THREAD

**Issue by ryancwalsh** [facebookresearch/loop#59]
**Hi @ytaigman @adampolyak   https://ytaigman.github.io/loop/ is one of the most exciting new technologies I've seen in a long time!**

**I'm excited to play with this.**

I've transcribed 99 minutes of recordings (10 seconds max each) and want to create my own TTS voice.

https://github.com/facebookresearch/loop#quick-start currently has these broken links:

* https://ytaigman.github.io/loop/demos/vctk_tutorial/p318_212.gen_10.wav
* https://ytaigman.github.io/loop/demos/vctk_tutorial/p318_212.orig.wav
* https://ytaigman.github.io/loop/demos/vctk_tutorial/p318_212.gen_14.wav

`pip install -r scripts/requirements.txt`, `bash scripts/download_data.sh`, and `bash scripts/download_models.sh`, seem to work fine.

But then `bash scripts/download_tools.sh` results in errors like:

```
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/c/code/voice_cloning/loop/merlin/tools/SPTK-3.9':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
./compile_tools.sh: line 35: make: command not found
./compile_tools.sh: line 36: make: command not found
downloading postfilter...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13986  100 13986    0     0   175k      0 --:--:-- --:--:-- --:--:--  175k
postfilter/src/SPTK/include: Can't create '\\\\?\\C:\\code\\voice_cloning\\loop\\merlin\\tools\\postfilter\\src\\SPTK\\include'
postfilter/src/SPTK/lib: Can't create '\\\\?\\C:\\code\\voice_cloning\\loop\\merlin\\tools\\postfilter\\src\\SPTK\\lib'
tar.exe: Error exit delayed from previous errors.
compiling postfilter...
./00_make.sh: line 5: aclocal: command not found
./00_make.sh: line 6: automake: command not found
./00_make.sh: line 7: autoconf: command not found
./00_make.sh: line 8: ./configure: No such file or directory
...
Error installing SPTK tools! Try installing dependencies!!
sudo apt-get install csh
```

I'm on Windows 10 using Anaconda. Is there some way to make this work?

More questions:

1. What does this mean? _"The preprocess pipeline can be executed using the following script by Kyle Kastner: https://gist.github.com/kastnerkyle/cc0ac48d34860c5bb3f9112f4d9a0300."_

1. What does _"Data should be downloaded and prepared as described above."_ mean in my case (wanting to create my own voice from 99+ mins of recordings)? Where do I put my own wav files and transcriptions, and how do I prepare them to be used?

1. Would you mind elaborating on the "Single-Speaker" and "Multi-Speaker" sections? What do those each mean? I assume I want the Single Speaker approach?

Thank you so much for this awesome project.

----------------

P.S. These commands (`python generate.py  --npz data/vctk/numpy_features_valid/p318_212.npz --spkr 13 --checkpoint models/vctk/bestmodel.pth` and `python generate.py  --text "hello world" --spkr 1 --checkpoint models/vctk/bestmodel.pth`) result in the following errors, which I'm assuming is because of the missing dependencies mentioned earlier:

```
(tensorflow) C:\code\voice_cloning\loop>python generate.py  --npz data/vctk/numpy_features_valid/p318_212.npz --spkr 13 --checkpoint models/vctk/bestmodel.pth
Traceback (most recent call last):
  File "generate.py", line 168, in <module>
    main()
  File "generate.py", line 102, in main
    model = Loop(train_args)
  File "C:\code\voice_cloning\loop\model.py", line 217, in __init__
    self.decoder = Decoder(opt)
  File "C:\code\voice_cloning\loop\model.py", line 137, in __init__
    opt.attention_alignment)
  File "C:\code\voice_cloning\loop\model.py", line 87, in __init__
    self.N_a = getLinear(mem_elem, 3*K)
  File "C:\code\voice_cloning\loop\model.py", line 15, in getLinear
    return nn.Sequential(nn.Linear(dim_in, dim_in/10),
  File "C:\code\Anaconda\envs\tensorflow\lib\site-packages\torch\nn\modules\linear.py", line 41, in __init__
    self.weight = Parameter(torch.Tensor(out_features, in_features))
TypeError: new() received an invalid combination of arguments - got (float, int), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the arguments have invalid types: ([31;1mfloat[0m, [31;1mint[0m)
 * (object data, torch.device device)
      didn't match because some of the arguments have invalid types: ([31;1mfloat[0m, [31;1mint[0m)
```

**Comment by wanshun123** [comment]
I ran into the "TypeError: new() received an invalid combination of arguments" issue as well running the command in quick start. Per https://github.com/facebookresearch/loop/issues/5 this only works with Python 2.7 (I was trying with Python 3.6).
