### ISSUE TITLE
Issue running install_tts.py to preprocess data

### ISSUE THREAD

**Issue by wanshun123** [facebookresearch/loop#62]
In order to preprocess new data to train on, the `install_tts.py` script at https://gist.github.com/kastnerkyle/001a58a58d090658ee5350cb6129f857 has to first be run (followed by `extract_feats.py` at https://gist.github.com/kastnerkyle/cc0ac48d34860c5bb3f9112f4d9a0300 which uses a file generated by `install_tts.py`). In running `install_tts.py` I'm getting the following error:

```
Traceback (most recent call last):
  File "install_tts.py", line 362, in <module>
    pe(configure_cmd)
  File "install_tts.py", line 116, in pe
    for line in execute(cmd, shell=shell):
  File "install_tts.py", line 107, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command '['./configure', '--with-fest-search-path=/home/paperspace/voiceloop/test/speech_synthesis/festival/examples', '--with-sptk-search-path=/home/paperspace/voiceloop/test/speech_synthesis/SPTK-3.9/bin', '--with-hts-search-path=/home/paperspace/voiceloop/test/speech_synthesis/htk/HTKTools', '--with-hts-engine-search-path=/home/paperspace/voiceloop/test/speech_synthesis/hts_engine_API-1.10/bin']' returned non-zero exit status 1
```

This is what my kk_all_deps.tar.gz file (required to run `install_tts.py`) file contains:

![Image of Yaktocat](https://i.imgur.com/jZrvsZI.png)

**Comment by wanshun123** [comment]
had to run the command with `sudo` (`sudo python2 install_tts.py`)
