### ISSUE TITLE
Error running train.py

### ISSUE THREAD

**Issue by sharonzhou** [facebookresearch/loop#63]
`AttributeError: 'module' object has no attribute '_cuda_setDevice'`

I'm using pytorch v0.1.12 per the docs.

When searching online, looks like a versioning problem with pytorch (interacting with CUDA) so this was unexpected. Any idea why this might be erroring? Tried uninstalling and reinstalling pytorch, but to no avail. Thanks!

**Full stacktrace**
> Traceback (most recent call last):
>   File "train.py", line 72, in <module>
>     torch.cuda.set_device(args.gpu)
>   File "path/to/my/miniconda2/envs/voiceloop/lib/python2.7/site-packages/torch/cuda/__init__.py", line 161, in set_device
>     torch._C._cuda_setDevice(device)
> AttributeError: 'module' object has no attribute '_cuda_setDevice'

**Comment by dmikushin** [comment]
This is because you are trying to use an unsupported version of pytorch. Please make sure you are using exactly the version specified in the README.
