### ISSUE TITLE
can not run the demo

### ISSUE THREAD

**Issue by seahearman** [facebookresearch/loop#7]
I tested the demo but failed

python generate.py  --text "hello world" --spkr 1 --checkpoint models/vctk/bestmodel.pth
Traceback (most recent call last):
  File "generate.py", line 153, in <module>
    main()
  File "generate.py", line 132, in main
    out, attn = model([txt, spkr], feat)
  File "/usr/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xinwang/voiceloop/loop/model.py", line 247, in forward
    context, ident = self.encoder(src[0], src[1])
  File "/usr/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xinwang/voiceloop/loop/model.py", line 66, in forward
    outputs = self.lut_p(input)
  File "/usr/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/torch/nn/modules/sparse.py", line 94, in forward
    self.scale_grad_by_freq, self.sparse
  File "/usr/local/lib/python2.7/site-packages/torch/nn/_functions/thnn/sparse.py", line 48, in forward
    cls._renorm(indices, weight, max_norm, norm_type)
TypeError: _renorm() takes exactly 5 arguments (4 given)

**Comment by jinserk** [comment]
you have to check pytorch version. the current code seems to work only on pytorch v0.1.12.

**Comment by abhinonymous** [comment]
`pip install http://download.pytorch.org/whl/cu80/torch-0.1.12.post2-cp27-none-linux_x86_64.whl`

For linux, python 2.7, cuda8, this should work for you
